resources:
  repositories:
    - repository: self
    - repository: tlpbb
      type: github
      endpoint: SkillsFundingAgency
      name: SkillsFundingAgency/tl-platform-building-blocks
      ref: TLD-172

trigger:
- master

stages:
  # - stage:
  #   displayName: 'Shared Infrastructure'
  #   jobs:
  #     - job: SharedInfrastructure
  #       pool:
  #         vmImage: ubuntu-latest
  #       steps:
  #       - checkout: self
  #         submodules: recursive
  #       - template: ./PipelineTemplates/deploy-template.yml@tlpbb
  #         parameters: 
  #           serviceConnection: '$(serviceConnectionName)'
  #           subscriptionId: '$(subscriptionId)'
  #           resourceGroupName: '$(sharedResourceGroupPrefix)-rg'
  #           location: 'westeurope'
  #           templateFilePath: './platform/azure/shared-template.bicep'
  #           processOutputs: false
  #           tags: '@{}'
  #           armParameterOverrideString: '-sharedResourceGroupPrefix $(sharedResourceGroupPrefix)'

  - stage: 
    displayName: 'Environment Infrastructure'
    jobs:
      - job: DeployInfrastructure
        pool:
          vmImage: ubuntu-latest
        steps:
        - checkout: self
          submodules: recursive
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: 'Resource Group'
            action: 'Create Or Update Resource Group'
            deploymentMode: Incremental
            azureResourceManagerConnection: '$(serviceConnectionName)'
            subscriptionId: '$(subscriptionId)'
            resourceGroupName: '$(resourceGroupPrefix)-rg'
            location: 'westeurope'
            templateLocation: 'Linked artifact'
            csmFile: './platform/azure/template.bicep'
            overrideParameters: '-resourceGroupPrefix $(resourceGroupPrefix) -appServicePlanTier $(appServicePlanTier) -appServicePlanInstances $(appServicePlanInstances)'
            deploymentOutputs: ArmTemplateOuputs