# initial template to try out submodule consumption

resources:
  repositories:
    - repository: self

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  submodules: recursive

- script: ls -lR
  displayName: 'Do a recursive directory listing'

- template: './tl-platform-building-blocks/PipelineTemplates/deploy-template.yml'
  parameters: 
    serviceConnection: 'Visual Studio Enterprise'
    subscriptionId: 'c6dfe75e-f5b6-4a81-952d-e0f6eadb4558'
    resourceGroupName: 'pipeline-rg'
    location: 'West Europe'
    templateFilePath: './tl-platform-building-blocks/ArmTemplates/app-service-plan-ase.json'
    processOutputs: true
    armParameterOverrideString: 
      '-appServicePlanName "pipeline-asp-01"
      -aspLocation "West Europe"
      -aspSize 1
      -aspInstances 1
      -nonASETier "Basic"'

    