# initial template to try out submodule consumption

resources:
  repositories:
    - repository: self
      persistCredentials: true
      clean: true

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: ls -lR
  displayName: 'Do a recursive directory listing'