resources:
  repositories:
    - repository: self
    - repository: tlpbb
      type: github
      endpoint: SkillsFundingAgency
      name: SkillsFundingAgency/tl-platform-building-blocks
      ref: feature/single-repo

trigger:
- master

stages:
  - stage:
    displayName: 'Shared Infrastructure'
    condition: false
    jobs:
      - job: SharedInfrastructure
        pool:
          vmImage: ubuntu-latest
        steps:
        - checkout: self
          submodules: recursive
        - template: ./PipelineTemplates/deploy-template.yml@tlpbb
          parameters: 
            serviceConnection: '$(serviceConnectionName)'
            subscriptionId: '$(subscriptionId)'
            resourceGroupName: '$(sharedResourceGroupPrefix)-rg'
            location: 'westeurope'
            templateFilePath: './platform/azure/shared-template.bicep'
            processOutputs: false
            tags: '@{}'
            armParameterOverrideString: '-sharedResourceGroupPrefix $(sharedResourceGroupPrefix)'

  - stage: 
    displayName: 'Environment Infrastructure'
    jobs:
      - job: DeployInfrastructure
        pool:
          vmImage: ubuntu-latest
        steps:
        - checkout: self
          submodules: recursive
        - template: ./PipelineTemplates/deploy-template.yml@tlpbb
          parameters: 
            serviceConnection: '$(serviceConnectionName)'
            subscriptionId: '$(subscriptionId)'
            resourceGroupName: '$(resourceGroupPrefix)-rg'
            location: 'westeurope'
            templateFilePath: './platform/azure/template.bicep'
            processOutputs: false
            tags: '@{}'
            armParameterOverrideString: '-resourceGroupPrefix $(resourceGroupPrefix) -appServicePlanTier $(appServicePlanTier) -appServicePlanInstances $(appServicePlanInstances)'
