# initial template to try out submodule consumption

resources:
  repositories:
    - repository: self
    - repository: tlpbb
      type: github
      endpoint: SkillsFundingAgency
      name: SkillsFundingAgency/tl-platform-building-blocks
      ref: feature/single-repo

trigger:
- master

jobs:
  - job: DeployInfrastructure
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
      submodules: recursive
    - template: ./PipelineTemplates/deploy-template.yml@tlpbb
      parameters: 
        serviceConnection: 'Visual Studio Enterprise'
        subscriptionId: 'c6dfe75e-f5b6-4a81-952d-e0f6eadb4558'
        resourceGroupName: 'pipeline-rg'
        location: 'westeurope'
        templateFilePath: './platform/template.bicep'
        processOutputs: true
        tags: '@{}'
