# initial template to try out submodule consumption

resources:
  repositories:
    - repository: self
    - repository: tlpbb
      type: github
      endpoint: SkillsFundingAgency
      name: SkillsFundingAgency/tl-platform-building-blocks
      ref: feature/single-repo

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  submodules: recursive

- script: ls -lR
  displayName: 'Do a recursive directory listing'

- template: ./PipelineTemplates/deploy-template.yml@tlpbb
  parameters: 
    serviceConnection: 'Visual Studio Enterprise'
    subscriptionId: 'c6dfe75e-f5b6-4a81-952d-e0f6eadb4558'
    resourceGroupName: 'pipeline-rg'
    location: 'westeurope'
    templateFilePath: './tl-platform-building-blocks/ArmTemplates/app-service-plan-ase.json'
    processOutputs: true
    tags: ""
    armParameterOverrideString: 
      '-appServicePlanName "pipeline-asp-01"
      -aspLocation "West Europe"
      -aspSize 1
      -aspInstances 1
      -nonASETier "Basic"'

    
